[package]
name = "stats-ci"
version = "0.0.1"
edition = "2021"

repository = "https://github.com/xdefago/stats-ci"
authors = ["xdefago"]

readme = "README.md"
license-file = "LICENSE.md"

description = "Provides functions to compute confidence intervals for various situations."
keywords = ["math", "statistics", "stats", "sampling", "analysis"]
categories = ["mathematics", "science", ]


[features]
default = ["serde"]
serde = ["dep:serde"]


[dependencies]
statrs = "0.16.0"
num-traits = "0.2.15"

thiserror = "1.0.30"
lazy_static = "1.4.0"
itertools = "0.10.5"

serde = { version = "1.0", optional = true, features = ["derive"] }

# dependencies for tests
[dev-dependencies]
assert_approx_eq = "1.1.0"
rand = "0.8.5"
